version: '3'
services:
    jenkins:
        build: .
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - "jenkins_home:/var/jenkins_home"
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - 1025:1025
            - 8025:8025
volumes:
    jenkins_home: